### ISSUE TITLE
Fix the behavior of `==` for upstream version match

### ISSUE THREAD

**Issue by cournape** [enthought/sat-solver#108]
`~=` has a different meaning in [PEP 440](https://www.python.org/dev/peps/pep-0440/#version-specifiers), so we should use a different syntax to avoid clashes. I would suggest something like `^=` or `#=`.

We should also change `==` to be consistent w/ PEP 440.
See alo [PEP 508](https://www.python.org/dev/peps/pep-0508/)

**Comment by cournape** [comment]
Fixed in #115

**Comment by johntyree** [comment]
We haven't fixed the behaviour of `==` yet, if that's necessary.

**Comment by cournape** [comment]
Indeed, we should fix that as well

**Comment by cournape** [comment]
Tracked more generally in #174
