### ISSUE TITLE
Add functionality to unlearn unit facts

### ISSUE THREAD

**Issue by jvkersch** [enthought/sat-solver#14]
Installed packages are described by unit facts. Sometimes, installing a new package will lead to conflicts, in which case the solver needs to figure out which packages to uninstall. This corresponds to unlearning unit facts. The solver already has (part of) this functionality. What is needed is:

- [ ] Add tests for the functionality to undo above the root level;
- [ ] Hook this up with the package manager.

**Comment by johntyree** [comment]
This issue is focused on an implementation detail that is no longer relevant. I will reopen an issue with the generalized idea.
