### ISSUE TITLE
Keep simplesat 0.7 on pypi

### ISSUE THREAD

**Issue by olofk** [enthought/sat-solver#259]
My application (https://github.com/olofk/fusesoc) has a dependency on simplesat. It would be great if you could keep version 0.7 on pypi, until I have made a new release that works with 0.8

**Comment by olofk** [comment]
My bad. It's still there. Just failed to understand the pypi web interface

**Comment by cournape** [comment]
Indeed, we never remove older releases.

0.8.0 should be backward compatible with 0.7.0. There is one change in practice `DependencySolver` where remote_repositories is enforced to be a list (this was not before, but the argument was not actually used, while it is now used).
