### ISSUE TITLE
The 0.9.0 wheel is broken

### ISSUE THREAD

**Issue by itziakos** [enthought/sat-solver#286]
There is a encoding error in the uploaded wheel. Need to fix the build scripts and upload a bugfix wheel asap

**Comment by alperyazar** [comment]
I can verify that the same problem exists on Python 3.6.

**Comment by itziakos** [comment]
reopen to avoid confusion. Will close when a fixed 0.9.1 wheel us uploaded to PyPI

**Comment by itziakos** [comment]
simplesat 0.9.1 has been released on PyPI
