### ISSUE TITLE
Fix the remove case

### ISSUE THREAD

**Issue by cournape** [enthought/sat-solver#43]
We need to be able to remove packages (and the packages that depend on those packages) with confirmation.

Eg. 
1. MKL, numpy and pandas installed
2. Ask to remove MKL
3. Confirm removal of MKL, numpy and pandas.
4. Remove all three.

**Comment by johntyree** [comment]
To achieve this, we could build a graph of the reverse dependencies of packages that are asking to be uninstalled, without bothering with any kind of SAT solving at all.

If `pandas` is installed and depends on `MKL` and we ask to uninstall `MKL`, we simply *must* uninstall `pandas`, there are no workable alternatives that I see.

So we start at each requirement, build the graph of (transitive) reverse dependencies, then ask for confirmation to uninstall all of them and we're done, right?

The only way I see that we might use the SAT solver here would be to do something tricky like having a request to uninstall `qtconsole` cause `ipython` to get downgraded to the highest version that doesn't depend on it. I don't think that's worth the trouble at all.

**Comment by johntyree** [comment]
Note that this is a *different* problem from the `ipython_downgrade` scenario, where we need to uninstall a package in order to get it out of the way (conflict) rather than because its dependencies are no longer satisfied.

**Comment by johntyree** [comment]
Another example, assume a package `A-0` depends on another `B-0`. A request to update `B` will be called unsatisfiable unless we are also free to remove `A-0`.

**Comment by johntyree** [comment]
After sketching out some more interesting scenarios while working on #60, I think does in fact have to go through the solver if we're going to do our best to preserve what is installed. The reason for this is that there might be a version of a reverse dependency which *doesn't* depend on the package being uninstalled and downgrading to that version is a possibility.

In this example we uninstall `requests`, a dependency of `browsey`, and can either downgrade to a different version of `browsey` which does not depend on `requests`, or we can remove `browsey` altogether. It's not clear to me which behavior is preferred.

```yaml
packages:
    - requests 2.7.0-1
    - browsey 1.1.0-1
    - browsey 1.2.0-1; depends (requests ~= 2.7.0)

installed:
    - requests 2.7.0-1
    - browsey 1.2.0-1

request:
    - kind: "remove"
      requirement: "requests"
```
