### ISSUE TITLE
Add tests for explicit package conflicts

### ISSUE THREAD

**Issue by cournape** [enthought/sat-solver#93]
We need to be able to express package conflict in our package metadata (and handle it in the SAT solver).

**Comment by johntyree** [comment]
We should talk about how to represent this. Is it going to be attached to each package? A separate index? Is there a notion of priority and who is authoritative on that?

I'm imagining that a `conflicts` declaration will be one-sided where the declaring side takes priority somehow, effectively treating them the way we treat packages with the same name but different versions currently.

This is tricky with things like `PIL` though. If someone asks to install `PIL` should we really? Should we not install `pillow` instead? It's easy to imagine it working this way when there is a linear progression from one package to the next via obsoletion, but what about "regular" conflicts, like having two well-maintained back-ends for some front-end system?

For that matter, we have no notion of a "provides" either. We need to make a list of the package relationships we expect to support.

**Comment by rkern** [comment]
A better example for a "regular" conflict would be two distributions providing a package with the same name, like [atom](https://pypi.python.org/pypi/atom) and [gdata](https://pypi.python.org/pypi/gdata), both of which provide completely different packages each named `atom`.

**Comment by cournape** [comment]
Let me first describe the notion of conflict. There are multiple notions of conflict

1. At a low level, two completely unrelated packages cannot be installed together. That's Robert's example. 
2. At a higher level, two packages cannot work together. That can happen because a package B fork of A becomes the "official" version, and the fork cannot be installed together w/ the forked version (the PIL / Pillow example). That can also be a package A, dependency of B, that has a specific version that does not work w/ a specific version of B. This is especially useful when a backward incompatibility is discovered "after the fact".

See also [composer require concepts](https://getcomposer.org/doc/04-schema.md#conflict) and [debian conflict section](https://www.debian.org/doc/debian-policy/ch-relationships.html). Note that we do not make a difference between breaks and conflicts, but the examples are good.

**Comment by cournape** [comment]
Now regarding the relation between conflict and provides: when multiple packages provide the same "interface" (think PIL vs Pilllow, but also numpy w/ MKL vs numpy w/o MKL), we would use the provide metadata to specify they can both provide a specific requirement. We would still need to say that each alternative providing a given requirement conflict w/ each other (if they do, which it is often but not always the case).

**Comment by cournape** [comment]
Implemented.

**Comment by johntyree** [comment]
As part of our lunch and learn, I had to prototype this `provides` feature as well (for `pil` vs `pillow`). I'm not sure it was the best approach, but it was very very simple, so I'll make a PR for it and we can discuss.
